server:
  port: 9090

eureka:
  instance:
    hostname: 172.16.10.42
    servicePort: 20080
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.servicePort}/eureka/

spring:
  application:
    name: app-server